# Generated by Django 5.2.14 on 2026-05-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientsession',
            new_name='subscriptio_status_ae0e9b_idx',
            old_name='subscriptio_status_c61d13_idx',
        ),
        migrations.RenameIndex(
            model_name='customer',
            new_name='subscriptio_name_7d2e50_idx',
            old_name='subscriptio_name_94c042_idx',
        ),
        migrations.RenameIndex(
            model_name='logentry',
            new_name='subscriptio_result_4bf419_idx',
            old_name='subscriptio_result_0a3c9c_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_status_067d55_idx',
            old_name='subscriptio_status_41ed2c_idx',
        ),
        migrations.RenameIndex(
            model_name='subscription',
            new_name='subscriptio_data_li_17b800_idx',
            old_name='subscriptio_data_li_efb7a4_idx',
        ),
    ]
